import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fl_chart/fl_chart.dart';

class HomeScreen extends ConsumerWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return SafeArea(
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildTopBar(),
            const SizedBox(height: 30),
            _buildSpendingSummary(),
            const SizedBox(height: 30),
            _buildChartSection(),
            const SizedBox(height: 40),
            const Text(
              'Recent Receipts',
              style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 16),
            
            // These will eventually be generated by a ListView.builder using your SQLite data
            _buildReceiptCard(
              merchantName: 'Walmart',
              category: 'Groceries',
              date: 'Mar 28, 2026',
              totalAmount: '\$142.50',
            ),
            const SizedBox(height: 16),
            _buildReceiptCard(
              merchantName: 'Starbucks',
              category: 'Food & Dining',
              date: 'Mar 27, 2026',
              totalAmount: '\$14.20',
            ),
            const SizedBox(height: 16),
            _buildReceiptCard(
              merchantName: 'Best Buy',
              category: 'Electronics',
              date: 'Mar 25, 2026',
              totalAmount: '\$89.99',
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTopBar() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        const Text(
          'Overview',
          style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold),
        ),
        _buildGlassContainer(
          padding: const EdgeInsets.all(8),
          child: const Icon(Icons.notifications_none, color: Colors.white),
        ),
      ],
    );
  }

  Widget _buildSpendingSummary() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        _buildGlassContainer(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          child: Row(
            children: const [
              Text('This Month', style: TextStyle(color: Colors.white)),
              SizedBox(width: 4),
              Icon(Icons.keyboard_arrow_down, color: Colors.white, size: 16),
            ],
          ),
        ),
        RichText(
          text: const TextSpan(
            text: 'Total Spent  ',
            style: TextStyle(color: Colors.white54, fontSize: 14),
            children: [
              TextSpan(
                text: '\$1,246.69', // This will be dynamic later
                style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildChartSection() {
    return SizedBox(
      height: 200,
      child: Stack(
        alignment: Alignment.center,
        children: [
          PieChart(
            PieChartData(
              sectionsSpace: 4,
              centerSpaceRadius: 75,
              startDegreeOffset: -90,
              sections: [
                PieChartSectionData(color: const Color(0xFFE1BEE7), value: 45, radius: 15, showTitle: false), // Groceries
                PieChartSectionData(color: const Color(0xFFB2DFDB), value: 25, radius: 15, showTitle: false), // Dining
                PieChartSectionData(color: const Color(0xFFFFF9C4), value: 20, radius: 15, showTitle: false), // Electronics
                PieChartSectionData(color: const Color(0xFF81D4FA), value: 10, radius: 15, showTitle: false), // Other
              ],
            ),
          ),
          Column(
            mainAxisSize: MainAxisSize.min,
            children: const [
              Text('\$1,246', style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold)),
              SizedBox(height: 4),
              Text('Total this month', style: TextStyle(color: Colors.white54, fontSize: 12)),
            ],
          ),
        ],
      ),
    );
  }

  // Dynamic helper to pick the right icon based on the AI's category categorization
  Map<String, dynamic> _getCategoryStyling(String category) {
    switch (category) {
      case 'Groceries':
        return {'icon': Icons.shopping_basket_outlined, 'color': const Color(0xFFE1BEE7)};
      case 'Food & Dining':
        return {'icon': Icons.restaurant_outlined, 'color': const Color(0xFFB2DFDB)};
      case 'Electronics':
        return {'icon': Icons.devices_other_outlined, 'color': const Color(0xFFFFF9C4)};
      default:
        return {'icon': Icons.receipt_long_outlined, 'color': const Color(0xFF81D4FA)};
    }
  }

  Widget _buildReceiptCard({
    required String merchantName,
    required String category,
    required String date,
    required String totalAmount,
  }) {
    final style = _getCategoryStyling(category);

    return _buildGlassContainer(
      padding: const EdgeInsets.all(16),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: style['color'],
              borderRadius: BorderRadius.circular(16),
            ),
            child: Icon(style['icon'], color: Colors.black87, size: 24),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(merchantName, style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600)),
                const SizedBox(height: 4),
                Text(category, style: const TextStyle(color: Colors.white54, fontSize: 13)),
              ],
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Text(totalAmount, style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),
              const SizedBox(height: 4),
              Text(date, style: const TextStyle(color: Colors.white54, fontSize: 12)),
            ],
          ),
        ],
      ),
    );
  }

  // The core Glassmorphism wrapper used throughout the screen
  Widget _buildGlassContainer({required Widget child, required EdgeInsets padding}) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.05), // Very transparent white fill
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white.withOpacity(0.1)), // Subtle white border
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20),
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10), // The frost effect
          child: Padding(
            padding: padding,
            child: child,
          ),
        ),
      ),
    );
  }
}